# Generated by Django 4.2.4 on 2023-09-07 19:35

from django.db import migrations, models

def update_category_name_field(apps, schema_editor):
   Category = apps.get_model('pchs', 'User_Name') 
   db_alias = schema_editor.connection.alias
   Category.objects.using(db_alias).filter(name='').update(name= 'Default Name')
class Migration(migrations.Migration):

    dependencies = [
        ('pchs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name="User_Name",
            name="name",
            field=models.CharField(max_length=100, blank=False)
            ),
            migrations.RunPython(update_category_name_field)
    ]
