# Generated by Django 4.2.4 on 2023-09-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pchs', '0002_user_name_com_password_user_name_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_name',
            name='user_name',
            field=models.CharField(default='0', max_length=200, unique=True),
        ),
    ]
