# Generated by Django 4.2.4 on 2023-09-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='0', max_length=200, unique=True)),
                ('first_name', models.CharField(default='0', max_length=300)),
                ('last_name', models.CharField(default='0', max_length=300)),
                ('email', models.CharField(default='0', max_length=300)),
                ('password', models.CharField(default='0', max_length=500)),
                ('com_password', models.CharField(default='0', max_length=500)),
                ('number', models.CharField(default='0', max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='0', max_length=20)),
                ('date_of_birth', models.DateField(default='0', max_length=20)),
            ],
        ),
    ]
