# Generated by Django 4.2.4 on 2023-10-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_re_delete_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Re',
            new_name='Registration',
        ),
    ]
